sudo: required
services:
  - docker

script:
 - docker build -t pkazmir/node .
 - docker images pkazmir/node

before_deploy:
  - docker login -u <username> -p <password>

deploy:
  provider: script
  script: docker push pkazmir/node
  on:
    branch: master
